name: build
on: [workflow_dispatch]
jobs:
  windows:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
    steps:
      - uses: actions/checkout@v2
      - name: Check out test data
        run: git clone https://github.com/mdbtools/mdbtestdata.git test
      - name: Autoconf
        run: |
          C:\msys64\usr\bin\bash -c -l 'pacman -Syu'
          C:\msys64\usr\bin\bash -c -l 'pacman -S autoconfig'
          C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && autoreconf -i -f'
      - name: Configure
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && ./configure'
      - name: Make
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && make'
      - name: Test
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && bash -e -x ./test_script.sh'
      - name: SQL Test
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && bash -e -x ./test_sql.sh'
